[theme]
# 暖色系のカラーテーマ設定

# メインカラー（ボタンやアクセント要素に使用）
primaryColor = "#E67E22"  # 深みのあるオレンジ

# 背景色
backgroundColor = "#FFF5E6"  # 明るいベージュ

# セカンダリ背景色（サイドバーやカード要素に使用）
secondaryBackgroundColor = "#FFE8CC"  # やさしいクリーム色

# テキストカラー
textColor = "#4A3526"  # 温かみのあるダークブラウン

# フォント設定
font = "sans serif"
