version: "3.9"
services:
  kotaemon:
    image: ghcr.io/cinnamon/kotaemon:main-full
    ports:
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./ktem_app_data:/app/ktem_app_data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    mem_limit: 4g
