model_list:
  # ----------------------------------------------
  # ===== Amazon Bedrock Claude Models =====
  # ----------------------------------------------
  - model_name: bedrock/claude-3-5-sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-east-1

  - model_name: bedrock/claude-3-5-sonnet-V2-Cross
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20241022-v2:0
      aws_region_name: us-east-1

  - model_name: bedrock/claude-3-5-sonnet-V1-Cross
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-east-1

  # ----------------------------------------------
  # ===== Amazon Bedrock Nova Models =====
  # ----------------------------------------------
  - model_name: bedrock/nova-micro
    litellm_params:
      model: bedrock/amazon.nova-micro-v1:0
      aws_region_name: us-east-1

  - model_name: bedrock/nova-lite
    litellm_params:
      model: bedrock/amazon.nova-lite-v1:0
      aws_region_name: us-east-1
        
  - model_name: bedrock/nova-pro
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0
      aws_region_name: us-east-1

  # ----------------------------------------------
  # ===== Amazon Bedrock Embedding Models =====
  # ----------------------------------------------
  - model_name: bedrock/amazon.titan-embed-text-v1
    litellm_params:
      model: bedrock/amazon.titan-embed-text-v1
      aws_region_name: us-east-1

  - model_name: bedrock/cohere.embed-english-v3
    litellm_params:
      model: bedrock/cohere.embed-english-v3
      aws_region_name: us-east-1

  - model_name: bedrock/cohere.embed-multilingual-v3
    litellm_params:
      model: bedrock/cohere.embed-multilingual-v3
      aws_region_name: us-east-1

  # ----------------------------------------------
  # ===== OpenAI Models =====
  # ----------------------------------------------
  - model_name: gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini                         # OpenAIのAPI呼び出しに使用
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o                         # OpenAIのAPI呼び出しに使用
      api_key: os.environ/OPENAI_API_KEY

  # ----------------------------------------------
  # ===== Anthropic Direct API Models =====
  # ----------------------------------------------
  - model_name: Anthropic/claude-3-5-sonnet-20240620    # Claude 3 Sonnet v1
    litellm_params: 
      model: claude-3-5-sonnet-20240620 
      api_key: "os.environ/ANTHROPIC_API_KEY" 

  - model_name: Anthropic/claude-3-5-sonnet-20241022    # Claude 3 Sonnet v2
    litellm_params: 
      model: claude-3-5-sonnet-20241022
      api_key: "os.environ/ANTHROPIC_API_KEY" 
      
  - model_name: Anthropic/claude-3-haiku-20240307       # Claude 3 Haiku
    litellm_params: 
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"

litellm_settings:
    drop_params: true
