version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-amaterasu1:/root/.ollama
    env_file:
      - .env
    pull_policy: always
    tty: true
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - open-webui-amaterasu1:/app/backend/data
      - ./:/work
      - ./backup:/backup
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-8181}:8080
    env_file:
      - .env
    environment:
      - 'RAG_WEB_LOADER_ENGINE=playwright'
      - 'PLAYWRIGHT_WS_URI=ws://playwright:3000'
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 open-webui
    depends_on:
      - open-webui
    restart: unless-stopped

  # バックアップ・リストア用のサービス
  backup-tool:
    image: ubuntu:latest
    volumes:
      - ollama-amaterasu1:/source/ollama
      - open-webui-amaterasu1:/source/webui
      - ./backup:/backup
    tty: true
    stdin_open: true
    command: bash

  playwright:
    image: mcr.microsoft.com/playwright:v1.49.1-noble # Version must match requirements.txt
    container_name: playwright
    command: npx -y playwright@1.49.1 run-server --port 3000 --host 0.0.0.0

volumes:
  ollama-amaterasu1: {}
  open-webui-amaterasu1: {}
