ss-mode:
 - DocuMind
docuMind-model: "gemini/gemini-1.5-flash"
docuMind-db: ".SourceSageAssets/DOCUMIND/Repository_summary.md"
docuMind-release-report: ".SourceSageAssets/RELEASE_REPORT/Report_v1.1.0.md"
docuMind-changelog: ".SourceSageAssets/Changelog/CHANGELOG_main.md"
docuMind-output: ".SourceSageAssets/DOCUMIND/RELEASE_NOTES_v1.1.0.md"
docuMind-prompt-output: ".SourceSageAssets/DOCUMIND/_PROMPT_v1.1.0.md"
repo-name: "AMATERASU"
repo-version: "v1.1.0"

# sourcesage --ss-mode=DocuMind --yaml-file=docs\.sourcesage_releasenotes.yml
